display_name: "E2 TTS"
paper: https://arxiv.org/abs/2406.18009
url: https://github.com/SWivid/F5-TTS
license: https://github.com/SWivid/F5-TTS/blob/main/LICENSE
release_date: 2024-10-13
languages:
  - en
  - zh
training_data: Emilia
training_hours: 95000
num_parameters: 333M
representations:
  - mel
features:
  - non-autoregressive
  - masked training
  - flow matching
citations: >
  @inproceedings{eskimez2024e2,
    title={E2 TTS: Embarrassingly easy fully non-autoregressive zero-shot tts},
    author={Eskimez, Sefik Emre and Wang, Xiaofei and Thakker, Manthan and Li, Canrun and Tsai, Chung-Hsien and Xiao, Zhen and Yang, Hemin and Zhu, Zirun and Tang, Min and Tan, Xu and others},
    booktitle={2024 IEEE Spoken Language Technology Workshop (SLT)},
    pages={682--689},
    year={2024},
    organization={IEEE}
  }
api:
  identifier: ttsds/e2
  version: 5ab0d513ddfb7cd35904877554773eabf0cc6c49a6a7a70f63aaae322d8767dc
  parameters:
    text: text
    speaker_reference: speaker_reference
    text_reference: text_reference
    language: null