display_name: "Fish Speech 1.2 (SFT)"
paper: https://arxiv.org/abs/2411.01156
url: https://github.com/fishaudio/fish-speech
license: https://github.com/fishaudio/fish-speech/blob/main/LICENSE
release_date: 2024-07-02
languages:
  - en
  - zh
  - ja
training_data: null
training_hours: 400000
num_parameters: 400M
representations:
  - quantized mel tokens
  - audio codec
features:
  - autoregressive
  - dual autoregressive
  - language modeling
citations: >
  @misc{fish-speech,
      title={Fish-Speech: Leveraging Large Language Models for Advanced Multilingual Text-to-Speech Synthesis},
      author={Shijia Liao and Yuxuan Wang and Tianyu Li and Yifan Cheng and Ruoyi Zhang and Rongzhi Zhou and Yijin Xing},
      year={2024},
      eprint={2411.01156},
      archivePrefix={arXiv},
      primaryClass={cs.SD},
      url={https://arxiv.org/abs/2411.01156},
  }
api:
  identifier: ttsds/fishspeech_1_2_sft
  version: 34a7e498d81e49e7200ee9aaa52f18b2529f30162ba6afd163b43037aa5a5d20
  parameters:
    text: text
    speaker_reference: speaker_reference
    text_reference: text_reference
    language: null