display_name: "Fish Speech 1.0 (Large)"
paper: https://arxiv.org/abs/2411.01156
url: https://github.com/fishaudio/fish-speech
license: https://github.com/fishaudio/fish-speech/blob/main/LICENSE
release_date: 2024-05-04
languages:
  - en
  - zh
  - ja
training_data: null
training_hours: 150000
num_parameters: 1B
representations:
  - quantized mel tokens
  - audio codec
features:
  - autoregressive
  - dual autoregressive
  - language modeling
citations: >
  @misc{fish-speech,
      title={Fish-Speech: Leveraging Large Language Models for Advanced Multilingual Text-to-Speech Synthesis},
      author={Shijia Liao and Yuxuan Wang and Tianyu Li and Yifan Cheng and Ruoyi Zhang and Rongzhi Zhou and Yijin Xing},
      year={2024},
      eprint={2411.01156},
      archivePrefix={arXiv},
      primaryClass={cs.SD},
      url={https://arxiv.org/abs/2411.01156},
  }
api:
  identifier: ttsds/fishspeech_1_0_large
  version: 067a41c0fcfcfebd7589bb45049a4d55cf91c0b2dac102020f5eb2f4990db8db
  parameters:
    text: text
    speaker_reference: speaker_reference
    text_reference: text_reference
    language: null