display_name: "MetaVoice-1B"
paper: null
url: https://github.com/metavoiceio/metavoice-src
license: https://github.com/metavoiceio/metavoice-src/blob/main/LICENSE
release_date: 2024-02-06
languages:
  - en
training_data: null
training_hours: 100000
num_parameters: 1.2B
representations:
  - audio codec
features:
  - non-autoregressive
  - autoregressive
  - language modeling
  - delay pattern
citations: >
  @misc{Sharma2024,
    author = {Sharma, Siddharth and Perić, Luca and Aggarwal, Vatsal and others},
    title = {MetaVoice},
    year = {2024},
    publisher = {GitHub},
    journal = {GitHub repository},
    howpublished = {\url{https://github.com/metavoiceio/metavoice-src}},
  }
api:
  identifier: ttsds/metavoice
  version: 3495610f45204d13509ef709586d9badd3bc4bd895aa712a252b249df6693143
  parameters:
    text: text
    speaker_reference: speaker_reference
    language: null
    text_reference: null