display_name: "Parler-TTS Tiny v1"
paper: https://arxiv.org/abs/2402.01912
url: https://github.com/huggingface/parler-tts
license: https://github.com/huggingface/parler-tts/blob/main/LICENSE
release_date: 2024-10-16
languages:
  - en
training_data: MLS
training_hours: 45000
num_parameters: 317M
representations:
  - audio codec
  - dac
features:
  - autoregressive
  - language modeling
  - delay pattern
citations: >
  @misc{lacombe-etal-2024-parler-tts,
    author = {Yoach Lacombe and Vaibhav Srivastav and Sanchit Gandhi},
    title = {Parler-TTS},
    year = {2024},
    publisher = {GitHub},
    journal = {GitHub repository},
    howpublished = {\url{https://github.com/huggingface/parler-tts}}
  }
  @misc{lyth2024natural,
        title={Natural language guidance of high-fidelity text-to-speech with synthetic annotations},
        author={Dan Lyth and Simon King},
        year={2024},
        eprint={2402.01912},
        archivePrefix={arXiv},
        primaryClass={cs.SD}
  }
api:
  identifier: ttsds/parlertts_tiny_1_0
  version: c789ab1e96d6ed5df17b34e3975552741bacf77b7561831f569b5187145db00f
  parameters:
    text: text
    speaker_reference: speaker_reference
    text_reference: text_reference
    language: null
    prompt:
      key: prompt
      value: ""