display_name: "Parler-TTS Mini Multilingual v1.1"
paper: https://arxiv.org/abs/2402.01912
url: https://github.com/huggingface/parler-tts
license: https://github.com/huggingface/parler-tts/blob/main/LICENSE
release_date: 2024-11-22
languages:
  - de
  - es
  - en
  - fr
  - it
  - nl
  - pl
  - pt
training_data: 
  - MLS
  - CML-TTS
training_hours: 20540
num_parameters: 880M
representations:
  - audio codec
  - dac
features:
  - autoregressive
  - language modeling
  - delay pattern
citations: >
  @misc{lacombe-etal-2024-parler-tts,
    author = {Yoach Lacombe and Vaibhav Srivastav and Sanchit Gandhi},
    title = {Parler-TTS},
    year = {2024},
    publisher = {GitHub},
    journal = {GitHub repository},
    howpublished = {\url{https://github.com/huggingface/parler-tts}}
  }
  @misc{lyth2024natural,
        title={Natural language guidance of high-fidelity text-to-speech with synthetic annotations},
        author={Dan Lyth and Simon King},
        year={2024},
        eprint={2402.01912},
        archivePrefix={arXiv},
        primaryClass={cs.SD}
  }
api:
  identifier: ttsds/parlertts_mini_multilingual_1_1
  version: 74c1dc4c8d7fbaf437290d6039d6a7b38e3df28727168a826244e3372a6ddc07
  parameters:
    text: text
    speaker_reference: speaker_reference
    text_reference: text_reference
    language: null
    prompt:
      key: prompt
      value: ""