display_name: "StyleTTS 2"
paper: https://arxiv.org/abs/2306.07691
url: https://github.com/yl4579/StyleTTS2
license: https://github.com/yl4579/StyleTTS2/blob/main/LICENSE
release_date: 2023-10-02
languages:
  - en
training_data:
  - LibriTTS
training_hours: 240
num_parameters: 191M
representations:
  - mel spectrogram
features:
  - non-autoregressive
  - grapheme-to-phoneme
  - diffusion
  - prosody prediction
citations: >
  @article{li2023styletts,
    title={Styletts 2: Towards human-level text-to-speech through style diffusion and adversarial training with large speech language models},
    author={Li, Yinghao Aaron and Han, Cong and Raghavan, Vinay and Mischler, Gavin and Mesgarani, Nima},
    journal={Advances in Neural Information Processing Systems},
    year={2023}
  }
api:
  identifier: ttsds/styletts2
  version: 296f82a3bcead1e194e74dd20d930708b92d89680d24fabb639a4e863a4832de
  parameters:
    text: text
    speaker_reference: speaker_reference
    text_reference: null
    language: null