display_name: "TorToise"
paper: https://arxiv.org/abs/2306.07691
url: https://github.com/afiaka87/tortoise-tts
license: https://github.com/afiaka87/tortoise-tts/blob/main/LICENSE
release_date: 2022-05-17
languages:
  - en
training_data:
  - LibriTTS
  - HifiTTS
  - Unknown
training_hours: 49500
num_parameters: 960M
representations:
  - mel spectrogram
features:
  - non-autoregressive
  - autoregressive
  - diffusion
  - language modeling
citations: >
  @misc{betker2023betterspeechsynthesisscaling,
    title={Better speech synthesis through scaling}, 
    author={James Betker},
    year={2023},
    eprint={2305.07243},
    archivePrefix={arXiv},
    primaryClass={cs.SD},
    url={https://arxiv.org/abs/2305.07243}, 
  }
api:
  identifier: ttsds/tortoise
  version: 274f7fd0812bba7717154110a0ffd2930db847135ab234e23a9d7c35924b8a09
  parameters:
    text: text
    speaker_reference: speaker_reference
    text_reference: null
    language: null