display_name: "VoiceCraft 830M"
paper: https://arxiv.org/abs/2403.16973
url: https://github.com/jasonppy/VoiceCraft
license: https://github.com/jasonppy/VoiceCraft/blob/main/LICENSE
release_date: 2024-03-28
languages:
  - en
training_data:
  - GigaSpeech
training_hours: 9000
num_parameters: 830M
representations:
  - audio codec
  - encodec
features:
  - autoregressive
  - grapheme-to-phoneme
  - delay pattern
  - language modeling
citations: >
  @article{peng2024voicecraft,
    author    = {Peng, Puyuan and Huang, Po-Yao and Mohamed, Abdelrahman and Harwath, David},
    title     = {VoiceCraft: Zero-Shot Speech Editing and Text-to-Speech in the Wild},
    journal   = {arXiv},
    year      = {2024},
  }
api:
  identifier: ttsds/voicecraft
  version: daee148e2e9d7cf3ae863c868f2ba23a15aa3dfba7700f49316f15028bbe7884
  parameters:
    text: text
    speaker_reference: speaker_reference
    text_reference: text_reference
    language: null
    args:
      version: giga830m_tts_enhanced