display_name: "WhisperSpeech Base"
paper: null
url: https://github.com/WhisperSpeech/WhisperSpeech
license: https://github.com/WhisperSpeech/WhisperSpeech/blob/main/LICENSE
release_date: 2024-01-22
languages:
  - en
  - pl
training_data:
  - MLS
  - LibriLight
training_hours: null
num_parameters: 132M
representations:
  - audio codec
  - encodec
features:
  - non-autoregressive
  - autoregressive
  - grapheme-to-phoneme
  - language modeling
citations: >
  @misc{WhisperSpeech2024,
    author = {Cłapa, Jakub Piotr and others},
    title = {WhisperSpeech},
    year = {2024},
    publisher = {GitHub},
    journal = {GitHub repository},
    howpublished = {\url{https://github.com/WhisperSpeech/WhisperSpeech}},
  }
api:
  identifier: ttsds/whisperspeech
  version: 9328cf0b16ea5fff4c986377ba9def07f5106e779e04fbf5754afa7cfff4c53c
  parameters:
    text: text
    speaker_reference: speaker_reference
    text_reference: null
    language: language
    args:
      version: base